---
- name: Fetch package | Kibana
  get_url:
    url: "https://download.elastic.co/kibana/kibana/kibana-{{ kibana_version }}-linux-x64.tar.gz"
    dest: "/tmp/kibana-{{ kibana_version }}-linux-x64.tar.gz"
  tags:
    - installation
    - kibana

- name: Directory Exists | /opt/kibana
  file:
    state: directory
    path: /opt/kibana
  tags:
    - directory-structure
    - kibana

- name: Unarchive package | Kibana
  unarchive:
    src: "/tmp/kibana-{{ kibana_version }}-linux-x64.tar.gz"
    dest: /opt/kibana
    copy: no
  tags:
    - installation
    - kibana
