---
- name: Upload startup script
  template:
    src: init.sh
    dest: /etc/init.d/kibana4
    mode: "u=xrw,g=r,o=r"

- name: Service start | kibana4
  service:
    state: started
    name: kibana4
  tags:
    - disruptive
